# Generated by Django 3.2.25 on 2026-01-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('blood_group', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('blood_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'blood',
                'managed': False,
            },
        ),
    ]
