# Generated by Django 3.2.25 on 2026-01-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('ambulance_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('contact', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ambulance',
                'managed': False,
            },
        ),
    ]
